create-unbound.sh and create-unbound.sh will now ignore empty entries…
uklans/cache-domains pull request #158
Opened 2021-01-17 18:44 UTC by systemofapwne

…, which may result into corrupt config files causing at least unbound (and probably also dnsmasq) to fail starting up

https://github.com/uklans/cache-domains/issues/157

### What CDN does this PR relate to

### Does this require running via sniproxy

### Capture method

### Testing Scenario

### Testing Configuration
```

```

### Sniproxy output
Please paste the output from `docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c` below
```

```

2021-01-21 00:25 UTC, nightah requested changes
Thanks for picking up on this and submitting the PR @systemofapwne.

While this doesn't cause an issue for dnsmasq it most definitely does for Unbound.
Having said that I believe the scripts can be simplified a little more, here's a patch detailing the changes I described in the review commentary:

```
Index: scripts/create-unbound.sh
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/create-unbound.sh b/scripts/create-unbound.sh
--- a/scripts/create-unbound.sh	(revision 019ec04f270e0b0d7b85dfb3d62ab1bfeb5d9d19)
+++ b/scripts/create-unbound.sh	(date 1611188130632)
@@ -45,16 +45,18 @@
 			destfilename=$(echo $filename | sed -e 's/txt/conf/')
 			outputfile=${outputdir}/${destfilename}
 			touch $outputfile
-			echo "server:" >> $outputfile
 			while read fileentry; do
-				# Ignore comments
-				if [[ $fileentry == \#* ]]; then
+				# Ignore comments and newlines
+				if [[ $fileentry == \#* ]] || [[ -z $fileentry ]]; then
 					continue
 				fi
 				parsed=$(echo $fileentry | sed -e "s/^\*\.//")
 				if grep -qx "$parsed" $outputfile; then
 					continue
 				fi
+        if [[ $(head -n 1 $outputfile) != "server:" ]]; then
+            echo "server:" >> $outputfile
+        fi
 				echo "  local-zone: \"${parsed}\" redirect" >> $outputfile
 				for i in ${cacheip}; do
 					echo "  local-data: \"${parsed} 30 IN A ${i}\"" >> $outputfile
Index: scripts/create-dnsmasq.sh
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/create-dnsmasq.sh b/scripts/create-dnsmasq.sh
--- a/scripts/create-dnsmasq.sh	(revision 019ec04f270e0b0d7b85dfb3d62ab1bfeb5d9d19)
+++ b/scripts/create-dnsmasq.sh	(date 1611188130622)
@@ -64,8 +64,8 @@
                         done <<< $(cat ${basedir}/$filename | sort);
                         # All other entries
                         while read -r fileentry; do
-                                # Ignore comments and wildcards
-                                if [[ $fileentry =~ ^(\#|\*\.) ]]; then
+                                # Ignore comments, newlines and wildcards
+                                if [[ $fileentry =~ ^(\#|\*\.) ]] || [[ -z $fileentry ]]; then
                                         continue
                                 fi
                                 parsed=$(echo $fileentry)
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-dnsmasq.sh
> +                                # Ignore empty lines
```suggestion
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-dnsmasq.sh
> +                                if [[ -z "$parsed" ]]; then
```suggestion
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-dnsmasq.sh
> +                                    continue
```suggestion
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-dnsmasq.sh
> +                                fi
```suggestion
```

This conditional can be merged with line 67-68:
```bash
                                # Ignore comments, newlines and wildcards
                                if [[ $fileentry =~ ^(\#|\*\.) ]] || [[ -z $fileentry ]]; then
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-unbound.sh
> +            isvalid=false
```suggestion
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-unbound.sh
> +                # Ignore empty lines
```suggestion
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-unbound.sh
> +                if [[ -z "$parsed" ]]; then
```suggestion
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-unbound.sh
> +                    continue
```suggestion
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-unbound.sh
> +                fi
```suggestion
```

This conditional can be merged with line 50-51:
```bash
				# Ignore comments and newlines
				if [[ $fileentry == \#* ]] || [[ -z $fileentry ]]; then
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-unbound.sh
> +                isvalid=true
```suggestion
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-unbound.sh
> +            # Delete files with no entries
```suggestion
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-unbound.sh
> +            if [[ $isvalid == false ]]; then
```suggestion
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-unbound.sh
> +                rm $outputfile
```suggestion
```

2021-01-21 00:25 UTC, nightah commented on scripts/create-unbound.sh
> +            fi
```suggestion
```

I think this logic can be simplified by only inserting "server:" if we have actually found matches.
So remove line 48 and add the following just before original line 58:
```bash
        if [[ $(head -n 1 $outputfile) != "server:" ]]; then
            echo "server:" >> $outputfile
        fi
```

I'll include a patch so you can in my review commentary too.

2021-01-27 22:36 UTC, systemofapwne commented
Sorry for the late feedback.
Your patch is way less redundent and more elegant compared to my quick & dirty hack.
I tested it and it reproduces almost the same output - It will still create obsolete empty files in the case for twitch (since twitch.json is empty), yet this is no problem for unbound.

So I totally approve this patch. Can the devs pick this up or shall I just recreate a new PR? At least I wonder, why the main repo ist not yet patched :)

2021-01-27 22:42 UTC, nightah commented
If you're not comfortable applying the patch to this PR I can take care of it.

Just let me know :).

2021-01-27 23:05 UTC, systemofapwne commented
> If you're not comfortable applying the patch to this PR I can take care of it.
> 
> Just let me know :).

Well, I screwed up my repo and instead of properly rebasing my repo back to 019ec04f  and patching the files, I branched it. I am now too tired to fix up the mess, so feel free to properly apply the patch to a dedicated PR.

2021-01-27 23:18 UTC, nightah commented
All done, just awaiting a review and merge.

Thanks for the report @systemofapwne!

2021-01-28 09:55 UTC, closed without merging

2021-01-28 09:55 UTC, VibroAxe commented
Thanks for the work on this @systemofapwne and @nightah