update Renegade X CDNs
uklans/cache-domains pull request #173
Opened 2021-08-21 16:57 UTC by matthewh86

### What CDN does this PR relate to

### Does this require running via sniproxy

### Capture method

### Testing Scenario

### Testing Configuration
```

```

### Sniproxy output
Please paste the output from `docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c` below
```
n/a
```

2021-08-21 17:35 UTC, GotenXiao commented
CC @Cronus89

2021-08-22 05:23 UTC, Cronus89 commented
Looks fine except remove
static.renegade-x.com
This should never be cached.

There are more changes, but I'll send those as a separate PR myself later. This gets the new servers in the list however :)

2021-08-22 08:20 UTC, MathewBurnett requested changes
Just that static content to remove and then this looks fine

2021-08-22 08:20 UTC, MathewBurnett commented on renegadex.txt
> +static.renegade-x.com
- [ ] remove static.renegade-x.com

2021-08-22 09:43 UTC, mintopia approved these changes

2021-08-22 09:44 UTC, merged

2021-08-22 09:44 UTC, mintopia commented
Thanks for the PR!